// Grouping of registry items for the section index pages. Components are
// grouped by interaction type; pages by aesthetic theme, except "Route
// transitions" which is a mechanic. Names must match `RegistryItem.name`.
// Ordering here is the display order; any item not listed falls into a
// trailing "More" group in the UI, so keep every item assigned. A test in
// tests/registry-integrity.test.mjs fails when anything is left ungrouped.

export interface RegistryGroup {
  title: string;
  names: string[];
}

export const componentGroups: RegistryGroup[] = [
  {
    title: "Layout, lists and widgets",
    names: [
      "falling-tag-list",
      "award-list",
      "portfolio-page",
      "creative-clutter",
      "animated-footer",
      "halftone-scene-footer",
      "vinyl-orbit-player",
      "physics-tag-footer",
      "image-explosion-footer",
      "circular-widget-dial",
      "drawn-path-features",
      "parallax-model-footer",
      "stacked-brand-cards",
      "service-index-scrub",
      "wrapped-drag-index",
      "filmstrip-video-player",
    ],
  },
  {
    title: "Preloaders and loaders",
    names: [
      "orbit-text-preloader",
      "counter-star-loader",
      "mask-reveal-preloader",
      "name-preloader-reveal",
      "preloader-panel-reveal",
      "landing-counter-reveal",
      "preloader-reveal",
      "split-reveal-preloader",
      "montage-reveal-hero",
      "landing-image-reveal",
      "circle-preloader-hero",
      "counter-word-preloader",
      "shuffle-grid-preloader",
      "card-fan-landing-reveal",
      "block-page-transition",
      "strip-merge-reveal",
      "emoji-trail-preloader",
      "odometer-load-hero",
      "scatter-letter-intro",
    ],
  },
  {
    title: "Hero sections",
    names: [
      "halftone-interface-hero",
      "ascii-tv-hero",
      "aperture-zoom-hero",
      "curtain-reveal-hero",
      "slit-reveal-hero",
      "frame-scroll",
      "inversa-scroll",
      "ascii-monogram-hero",
      "frame-sequence-hero",
      "gravity-drop-landing",
    ],
  },
  {
    title: "Galleries and grids",
    names: [
      "spiral-gallery",
      "scroll-wave-gallery",
      "shader-grid-gallery",
      "catalog-swap-gallery",
      "filter-scrub-gallery",
      "spotlight-gallery-scroll",
      "spotlight-index-scroll",
      "mosaic-flip",
      "fluid-mosaic",
      "ascii-image-reveal",
      "image-reveal",
      "liquid-stat-grid",
      "curve-gallery",
      "carousel-ring-gallery",
      "photo-sphere-orb",
      "infinite-drag-canvas",
      "swing-in-work-grid",
      "pinned-scale-mosaic",
      "masked-spotlight-scroll",
      "wedge-clip-work-scroll",
      "cylinder-block-gallery",
      "flip-tile-board",
      "contact-sheet-zoom",
      "flip-layout-gallery",
      "carousel-disc-scroll",
      "radial-name-wheel",
      "pan-video-canvas",
    ],
  },
  {
    title: "Sliders and carousels",
    names: [
      "voku-image-slider",
      "threejs-infinite-slider",
      "scroll-scrub-slider",
      "hour-timeline-slider",
      "depoluxe-sideways-carousel",
      "detroit-paris-slider",
      "curved-plane-slider",
      "minimap-scrubber",
      "minimap-parallax-scroll",
      "drag-timeline-scroll",
      "split-column-infinite-slider",
      "dial-product-slider",
      "parallax-drag-rail",
      "endless-side-story",
      "marquee-carousel-scroll",
      "throw-away-work-slider",
      "flip-marquee-horizontal",
      "sticky-parallax-slides",
      "snap-parallax-projects",
      "shader-warp-slider",
      "magnetic-spotlight-marquee",
      "wheel-clip-slider",
      "rotating-panel-slider",
      "split-click-slider",
      "letter-grid-carousel",
      "split-plate-slider",
      "diagonal-plate-carousel",
      "liquid-glass-carousel",
    ],
  },
  {
    title: "Cards and stacks",
    names: [
      "video-card-stack",
      "split-card-scroll",
      "scroll-flip-cards",
      "sticky-flip-cards",
      "tilt-card-stack",
      "sticky-stack-cards",
      "fanned-card-deck",
      "dealt-team-cards",
      "deal-stack-cards-scroll",
      "pushup-card-stack",
      "card-parting-reveal",
      "calendar-pad-cards",
      "pinned-shrink-cards",
    ],
  },
  {
    title: "Text effects",
    names: [
      "text-displacement-field",
      "scroll-text-blocks",
      "line-rise-text",
      "block-reveal-text",
      "terminal-text-reveal",
      "word-highlight-scroll",
      "stretch-text-scroll",
      "converging-icons-text",
      "converging-search-scroll",
      "flow-field-text",
      "wordmark-spotlight-scroll",
      "interlock-title-scroll",
      "skew-char-header",
      "curved-letter-path-scroll",
      "clip-reveal-services",
      "pixel-smear-wordmark",
    ],
  },
  {
    title: "Cursor and hover effects",
    names: [
      "grid-scramble-hover",
      "client-hover-preview",
      "folder-preview-hover",
      "inversion-lens-hover",
      "fractal-glass-hover",
      "svg-stroke-hover",
      "cursor-trail-scroll",
      "cursor-image-trail",
      "smudge-cursor-reveal",
      "sandy-grain-background",
      "sunlit",
      "accordion-frames",
    ],
  },
  {
    title: "Menus and navigation",
    names: [
      "model-menu-3d",
      "overlay-menu",
      "expanding-navbar-reveal",
      "folding-panel-menu",
      "sliding-index-menu",
      "elastic-curtain-menu",
      "tilt-away-menu",
      "push-down-overlay-menu",
      "rotating-halves-menu",
      "shuffle-panel-menu",
      "story-reel-viewer",
    ],
  },
  {
    title: "Scroll sequences",
    names: [
      "ribbon-stroke-scroll",
      "cross-reveal-scroll",
      "arc-spotlight-scroll",
      "rotating-hand-scroll",
      "infinite-contact-scroll",
      "webgl-dissolve-scroll",
      "stroke-wipe-spotlight",
      "showreel-zoom-scroll",
      "starfield-warp-scroll",
      "triangle-fill-scroll",
      "nested-mask-banner",
      "logo-mask-zoom-scroll",
      "cycle-scrub-showcase",
      "drifting-card-marquee",
    ],
  },
  {
    title: "3D and WebGL scenes",
    names: [
      "scroll-tunnel-3d",
      "corridor-scene-3d",
      "cappen-fluid-simulation",
      "crt-display",
      "ascii-logo",
      "material-spotlight",
      "drone-fleet",
      "motion-tracking",
      "lego-dither",
      "ink-field",
      "prism-light-instrument",
      "starry-night-flow",
      "flying-cube-scroll",
      "surprise-box",
      "floating-model-scroll",
      "garage-scene-3d",
      "particle-fluid-hero",
      "shader-tunnel-slider",
      "lava-particle-field",
      "scatter-photo-physics",
      "pixel-cube-avatar",
      "pixel-cube-field",
      "elastic-string-field",
      "wind-drift-field",
    ],
  },
];

export const pageGroups: RegistryGroup[] = [
  {
    title: "Minimal and refined",
    names: [
      "interior-studio-page",
      "isochrome-page",
      "damien-tsarantos-page",
      "dither-studio-page",
    ],
  },
  {
    title: "Editorial and typographic",
    names: [
      "march-2025-template",
      "archive-commerce-page",
      "house-of-epochs-page",
      "dining-room-page",
      "expanding-rows-gallery",
      "content-architecture-page",
    ],
  },
  {
    title: "Creative studio and experimental",
    names: [
      "blnk-agency-page",
      "wu-wei-page",
      "lemon-bureau-page",
      "null-studio-page",
      "ink-core-layout",
      "neoteric-page",
      "unusual-studio-page",
      "otis-valen-page",
      "polite-chaos-page",
      "pixelgrid-studio-page",
      "edge-warp-rail",
    ],
  },
  {
    // The one page group defined by mechanic rather than look: these are
    // multi-route templates whose whole point is what happens between pages.
    title: "Route transitions",
    names: [
      "clip-mask-transition-page",
      "view-transition-folio-page",
      "revealer-transition-page",
      "block-logo-transition-page",
      "monogram-morph-page",
      "scroll-advance-project-page",
    ],
  },
  {
    title: "Dark and cinematic",
    names: [
      "chrome-folio-page",
      "procedural-computer-page",
      "film-studio-page",
      "dark-catalog-page",
      "deadspace-page",
      "velasco-solari-page",
      "orbit-matter-page",
    ],
  },
  {
    title: "Brutalist and raw",
    names: ["brutalist-portfolio-page"],
  },
  {
    title: "Playful and dimensional",
    names: ["soren-page"],
  },
];

export const backendGroups: RegistryGroup[] = [
  {
    title: "Runtime-native building blocks",
    names: [
      "bun-secrets-vault",
      "bun-sqlite-job-queue",
      "bun-auth-gateway",
      "deno-kv-leader-election",
      "deno-kv-rate-limit",
      "deno-kv-realtime-sync",
      "node-permission-sandbox",
      "node-diagnostics-telemetry",
      "node-sqlite-worker-pool",
      "durable-object-rpc-rate-limit",
    ],
  },
  {
    title: "Auth and access control",
    names: [
      "alchemy-cloudflare-access-gateway",
      "better-auth-jwks-cookie-cache",
      "better-auth-provisioning-gate",
      "better-auth-atomic-rate-limit",
    ],
  },
  {
    title: "Databases and queries",
    names: [
      "effect-sql-transactional-repository",
      "prisma-driver-adapter-runtime",
      "prisma-client-extension-audit",
      "drizzle-pg-jit-query-layer",
      "drizzle-cache-tag-invalidation",
      "drizzle-kit-migration-gate",
      "drizzle-effect-pg-repository",
      "neon-http-composable-sql",
      "d1-session-read-replica",
      "durable-object-sql-tenant-db",
      "pg-advisory-lock-keyset-scan",
      "indexeddb-sync-outbox",
      "turso-replica-read-your-writes",
      "turso-tenant-migration-fanout",
      "turso-transaction-mode-guard",
    ],
  },
  {
    title: "Failure-mode resilience",
    names: [
      "effect-cache-stampede-guard",
      "effect-circuit-breaker-budget",
      "effect-shard-router-backpressure",
      "effect-fencing-token-hlc",
      "effect-outbox-replicator",
    ],
  },
  {
    title: "Distributed systems patterns",
    names: [
      "effect-idempotency-key-store",
      "effect-exactly-once-consumer",
      "effect-hedged-request-race",
      "effect-bulkhead-isolation",
      "effect-read-replica-router",
      "effect-consistent-hash-ring",
      "effect-heartbeat-failure-detector",
      "effect-snowflake-id-generator",
      "effect-multipart-upload-resume",
      "effect-webhook-dispatcher",
      "effect-optimistic-lock-retry",
      "effect-deadlock-detector",
      "effect-quorum-read-repair",
      "effect-bloom-url-frontier",
      "effect-geohash-proximity",
      "effect-password-hash-vault",
      "effect-payment-reconciliation",
      "effect-hot-account-ledger",
      "convex-exactly-once-action",
    ],
  },
  {
    title: "Caching and edge delivery",
    names: [
      "effect-weighted-load-balancer",
      "effect-lru-cache-eviction",
      "effect-write-behind-cache",
      "effect-cache-penetration-shield",
      "effect-cdn-origin-shield",
      "effect-dns-resolver-cache",
    ],
  },
  {
    title: "Storage engines and transactions",
    names: [
      "effect-mvcc-snapshot-isolation",
      "effect-event-sourced-aggregate",
      "effect-lsm-memtable-compaction",
      "effect-wal-crash-recovery",
      "effect-two-phase-commit",
      "effect-saga-payment-orchestrator",
      "convex-occ-sharded-counter",
      "tigerbeetle-test-ledger",
      "tigerbeetle-two-phase-reservation",
    ],
  },
  {
    title: "Coordination and replication",
    names: [
      "effect-leader-lease-election",
      "effect-vector-clock-causality",
      "effect-merkle-anti-entropy",
      "effect-gossip-dissemination",
      "effect-crdt-counter-merge",
      "effect-scatter-gather-quorum",
    ],
  },
  {
    title: "Traffic control and throughput",
    names: [
      "effect-token-bucket-shaper",
      "effect-sliding-window-rate-limit",
      "effect-adaptive-concurrency-limit",
      "effect-connection-pool-fair",
      "effect-fair-priority-scheduler",
      "effect-dataloader-batch",
      "effect-chunked-upload-integrity",
      "vercel-ai-gateway-failover-budget",
    ],
  },
  {
    title: "Durable workflows and jobs",
    names: [
      "effect-durable-activity-workflow",
      "effect-durable-workflow-queue",
      "effect-workflow-v4-migration",
      "cloudflare-workflow-saga-rollback",
      "durable-object-alarm-scheduler",
      "rivet-durable-workflow-actor",
      "rivet-dynamic-actor-registry",
      "vercel-queue-consumer-groups",
      "artifacts-fork-run-workflow",
      "effect-cluster-entity-sharding",
      "vercel-workflow-step-idempotency",
      "vercel-workflow-continuation-versioning",
    ],
  },
  {
    title: "Edge runtimes and caching",
    names: [
      "effect-cloudflare-event-api",
      "cloudflare-worker-cache-tags",
      "cloudflare-worker-test-harness",
      "durable-object-websocket-hibernation",
      "worker-rpc-promise-pipelining",
      "effect-rpc-contract-transport",
      "effect-service-lifecycle-runtime",
      "fluid-compute-instance-safety",
      "fluid-stream-lifecycle",
      "artifacts-repo-provisioner",
      "artifacts-agent-commit-notes",
      "vercel-waituntil-drain-guard",
      "vercel-blob-client-upload-tokens",
    ],
  },
  {
    title: "Browser runtime and messaging",
    names: ["effect-browser-peer-channel"],
  },
  {
    title: "API servers and routing",
    names: [
      "effect-httpapi-derived-client",
      "elysia-plugin-scope-model",
      "elysia-aot-build-manifest",
      "elysia-standard-schema-guard",
      "websocket-route-handler",
    ],
  },
  {
    title: "Framework data loading",
    names: [
      "sveltekit-live-query-stream",
      "sveltekit-batched-query-refresh",
      "sveltekit-explicit-env-vars",
    ],
  },
];

export const registryGroupsBySection: Record<string, RegistryGroup[]> = {
  components: componentGroups,
  pages: pageGroups,
  backend: backendGroups,
};
