/**
 * Glyph-field model for the benefits section.
 *
 * The field renders a "model" region whose per-cell brightness decides which
 * cells burn bright, so the artwork reads as a silhouette drawn in claim text.
 * The grid is 160x88 cells at glyphAspect 0.55, which is a square source
 * squashed onto non-square cells, matching how the field samples it.
 *
 * Generated from the BLANK hand asset (animated-footer/blank-hand-right.png):
 * resized to the cell grid, inverted (the source art is a dark hand on a light
 * ground, the model wants the subject bright), then autocontrasted. Baked in
 * rather than fetched so the field never waits on the network to draw.
 */

export const HAND_MODEL_COLUMNS = 160;
export const HAND_MODEL_ROWS = 88;

const HAND_MODEL_BASE64 =
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEBAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwJRwQDAsDAAAAAAAAAAAA" +
  "AAAAAAEBAQEBAQEBAQEBAQEBAAAAAAAAAAAAAAAAAAABAQEBAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "UFFWT0hIPjw3LSQcFxALBQMCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAQAAAQEBAQEAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAExLS01LSFJQT1ZPS0xGQTszMi4uLCYlIyEdGxoYFhAQDwwJBgYGBgUFAgEAAAABBA8eKykjHhIH" +
  "AQAAAAAAAAAAAAAAAAAAAAEBAQEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABZWE5PUEFAPURPT09PTktLTVBORUlAREZBQkE9Ozs4ODYxLS8xList" +
  "Ky8pJyEgJCU0PkxNTU5RRT4xJRgOCQkNDg8QDwsGAwAAAAAAAAAAAAABAQEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaV5oZWVbXEVJUT1LRkJARkJJTUVEODw8" +
  "MS4pKystMTM5Ojs9RENJQkBCQkI6Mi4tJyEhLDIwMDpBQERGQjsxMDEvMTI2Oz5AOjYwJBwRCAIAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAEBAQEBAQICAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGZkYlliaGxg" +
  "UExIVltPR0hGQUFGPkJMUlxTVlZWVkxGQ0A8PUJBS0hOUU5OSE9QSEZFUmNeWldJTU5VUEZRSE1HVUlMRzYwOEdTV11hXVJN" +
  "SDsxKyYjIB0hGSAoJhoSDw4LBgIAAAAAAAAAAAAAAAAAAAIBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAABnZXBsZmVwdXViWF1oXlxZa1lca3VxhIGGfIGBfoR9bWdkWVZJREZHTEhIS01RU1ddYFtgW11iV1ddW09JRjs8" +
  "TFVbZ2tzeWdIOUJYaGdmbnFsZWBeW1laUlBWW1xTUFdWUU5JRkE+Ni86KDNAODYlEQAAAAAAAAEBAQEAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgHOAjIV3dnqCc3V2e2dtZ2duWmdzcWtgaWdeXWReY1xpYltiXmdlZ2tVYF5PSE9N" +
  "UldgU1hORENDQkZLVVhZXWVse4mQnaarnXpYPFBzjpKPgnh4cmddU09YXFxdYVtjVlBYU1poYmJdXWFjbG1ZVmleNywlEQQA" +
  "AAAAAAABAgEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJKViIaTkYB3fXN2dnV2aVxicllVV11bWltZTEhQR0VQ" +
  "SE9PU15aXFxkaHJwXU5GR01LR0tHRjw+PDxCRUxkcIOPkaets7m6w7azq4tjTWmgy7uqnomCg4OHi4iQl5ODeXdxbmtpcXly" +
  "hpGOhX16iZuvroeAdm9hSzcoFgcAAAAAAAABAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACbloyCjnVweG56b3FtYnxl" +
  "Y1hgVVZRVlFRU05NQD1GSEtNQ0RNRERPaWVmY2FgWVtPVU5NR0hMUVdZVlZTWmJyiKGyt7y+w8fDwsLBsotjXJns3Ly8t7W4" +
  "vLm7wsG6sa2rq6utp6KjoJutp6Skus25mX1zb29rZWVpb2hiWEUvHQwAAAAAAAACAgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "iI6Hgn11dmtra1hrZmVlb2ljXmVjYFxYXFtiWlFOTkNCRUhGR0lPUldWW05SVk1RUVpcTlFhaXJ6dXZ8eXN1gZKgp7W2uLy5" +
  "rZuYmpeipYZpgL3n8OPc293h3t7b18/Pz8fI0NLRzMjEu7ezs7WwnpaYkpCFfHJoa3BpZ2lyd3ZsY0w0IAwAAAAAAQIBAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAIZ+enhudXVra2xna11nbnVxb2ZdZ2RPVmFoYGNgXWlhUlBSUUdFQ1BRU01PT1BEUFFGSUZIS0dR" +
  "U1JTXGNseIWWnqSvr6yxpJeIdW9wcniJloNtdrHm/P347+zo5eLg29fR0trb2tnX09LS09PT09HLx72xrqealY2Cd3JtbWll" +
  "bX58hndyZ08tDQAAAAEBAAAAAAAAAAAAAAAAAAAAAACCc253fHp7eXFxg2JmWWt8YmNhWlpgZVFYYWhiZFtgYlhXWVlNUk5H" +
  "Tk9MSUJCREhIRENDQzo2OTpETlNYYWdxhJCXnqGgmpKSl56nqJeJhX54cl1NXZe+4vn58OXj4dzd4ePc0tPc3djX2d3l5+fg" +
  "2tXQz8zDxL23s6OgmZKRjIyTko2Eh4uYlYFdLhEAAAACAQEAAAAAAAAAAAAAAAAAhYF5g4V7d3Fydn11fGt6g2VlWmxcY1pS" +
  "VVNZXG9pXGJaYFddXW1kWWBWU05FRkFGS0lOR0lOUVFSXmdwc36GiZGanJaepa61wMvZ2tLDsrWlg3BwbW1wZ3OHtdDk5OHZ" +
  "1dfc497a297e29je5+Dk5ebk4+Tg2tnY1dHMyMXGw76+wb2sm46PjYONnKSIXScBAAAAAAIBAAAAAAAAAAAAAKKOjZyNgH52" +
  "d3d6goSFg4R6gYh3cHJlVlFTWFpoa2ZnbVxZXGJmZ2JydW9vZmBZU1lPTFVdbm9tbXF5e4WRnaitq6aSjZ6wttDi4ePk1szL" +
  "uqKOgnVsZ2FiXVVdeJe5z9vd29fX2tze4+bs8vPr4dzX2+Dd3NnW2NbX19XX3t3c29fQwbmxppuampWbe3J4Wj4lDwAAAAAA" +
  "AAAAAAAAAACioqydi4aFhYeIhYyTjJWDi4ymmImHeXNYXlxbVmBhXFxOYGBpcnBven15foGJiX19a2RmZWlvbnZ+goWHj52h" +
  "mpWXjpCEdnOBuu768ufg2cu8qJuNgHJ7cXBtaGNibIGZu9bk5eDRxb2yori9xOHr6+fj4eDX1dXSz9DOz9PW29vZ0svIw8C4" +
  "r6ihlZF3cnJxbGRaRhwAAAAAAAAAAAAAtryrl5CMiY+Ffn6YlZicmainlq2Zmp2QhH58b2R1Zlxlb2lhZ2lxbHJzaVxtdXmC" +
  "iIGHi5CHiYWGkZqRi4mDgHJpbnqBd15na2+Px/3/9+jc0sW6saaeoZeMhn12d3h9cXyMd0w0KxsOAQADBgktYISkwdXh5ezu" +
  "7u7u7e7u7u7l4Nza1c/T083Btaybh3ZtZWVtdpGZCwABAAAAAAAAAMa3o5GNk5aIfYOCiZKQobe3sKyura/Bu7OXmI6QhXJ5" +
  "fWhiYmNkbWRjZF1YS1JcZWxye4CPl56mp56mpaCShIB8eH2GgHhziJmOeGiJ1f//+uja0se8tbGnopmMgXt4hYKMhIFeKwAA" +
  "AAACAAAAAAAAAAsdL0RXZHmHmKWttqu1z+j19fDm4d7X1tHRzbuuo4uBgpPRqAQBAAAAAAAAAAC3sJyLk5eOhX2HjYiQlqOy" +
  "s7W5ubu8usjEw7e6s6+qoY52gm1uZmhaV1lWU1ZebHBnb3Z9kKezvMXGxsTExsXLysjDr5uPh4BzbG1rb2Z5u/L//+/h183D" +
  "ua6koI+Oi4iQkH2CmaxsMxAAAAACAQIDAgEAAAAAAAAAAAAAAAAAABM3ZpvE4e718/Pw7Orn5eDZ09jhsSAAAQAAAAAAAAAA" +
  "sraVl6ePhYuOj5WMjJigq7W+tbrAxMfP3NXMzs/FsaioqKKDeHloY2NcYWRvhZKSmI2Rm6azvdHd5Obm5uvq6ubh2Me1raWS" +
  "h4SEdnBtYFNmkcTx//Xl2tLDu7KrpZyWlpOPgHNxhIORcisEAAABAAAAAQECAwMDAwICAQAAAAAAAAAACSREbJOyx9ba3N3X" +
  "zrqSTQMAAQAAAAAAAAAAAMK4q6+soJ2bpaahoqSopa+7ubm+wsTIztvk3tna1r2wxLebl5WDfn11d36Ai5CkvMOzqKy3xNHk" +
  "6uvw8/P19vfx6+DWy76xp5qPg3htaWhubWhdcqDQ8fnr3NrVx723ta+vpJOWgXWXkIGJbDwIAAEAAAAAAAAAAAAAAAAAAAAA" +
  "AQIDAQAAAAAAAAYTGh4cGQ8BAAAAAQAAAAAAAAAAAADMu8K+vbiyuby7sba6tbfAwrzAw8TKyszO3eTb19PRvMHCsaiijY6B" +
  "hHuCgYGQpLi+xcTKztLW3eby+fz7/P///fLr4tfQwK6jopKJfHN5go2GhYZ6dYu95vzx5t7a0MbNzb28vLCZkXN1h42GbhgA" +
  "AgEAAAAAAAAAAAAAAAAAAAAAAAABAgMDAgAAAAAAAAAAAAIDAQAAAAAAAAAAAAAA19XXzsfFys/Ly8TDys3KyMvHx8vGz8vI" +
  "zsjS09HR0cPExbKtpqaoo52WhH6BgY6erLW+ysvHy8vO2u39////////+fHk2s7EvrGcnZ2ZlpmWkY+Wp6SWjY687//37efj" +
  "4uDa083QyMzKyMGdi5BxIAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAgEBAQAAAAAAAAAAAAAAAAAAAN7m29DS0tfc" +
  "2NPW0tfW2NLV2NfW0dXQz9HCytLV1dDLyMa6t7y8xMjFvrWxq56cmpqcpbC2rrG3tri2ucbt////////9+7o4dbNxLmyr6um" +
  "opycoKijqKukk5bB6//98u7q6OHZ2Nni6+rm2tbMs4lHCQABAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAADq6uLe5OTg5OHd2tnc3ODc3ePd5ODg4N3azs/V1dHRy7q9yMTHztLY1dLQxsHAua6jp6SipKWhnaKbmI56h7fv" +
  "/////////Pfr4NvWy8C5vLevrrC2ubWzu7m1o4us4P//8+/o3tPLxsvWzMK8squkkWklAAABAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7uzt7O7r5OTi4uDe5+fn5OTn4ufm5uXk4tvd29vX0tDHytXT0tfe4OPr3NHQzcS+" +
  "wMXBsqiknZeVj5B1cHBxgKzy//////////rz7OHa0sjGvLGwrLCzvcXPvJ2RjZe34v/48u7n4NjOxry1srXAuaySflcXAAAB" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPXy7uzs7Orn5ebl5+zu7evq6ubn6uXi4+jj4eLi087P" +
  "19na3d3e4+br9u3d4NrQ0NXb2sjAu6+qpZiGenaAend+hL7///////////vz8Ovd1cy+uLCzt7Kump2rxcClm53M/fv29fHv" +
  "6uLY1c/PzsK4mo6VhUADAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADX6/f8///38Ovq6+zw7+3t" +
  "6+3w8O7o5Ofs5+ru49zc3Nvh4+Dg5eTm7ff55efj293t9eTPzMa4r6OWi4+RnJWaoaCYpdH7/////////fv48+vi0cvGw8Kz" +
  "pJyzwJ6lyt7c3OX///v6+PLr4NbQxbyyraWdmJ2eZxoAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "ECY8VXyw0ej3/f/69fDu7evr8O/t7u3s7eru8Ofj5Obr8Ofi5uvu7u7z/+/o5+bs///m2dHFvrqnp62lp6ursbPCwru6rtf/" +
  "+P//+Pr////79u3m4tnPx7i9u7O4zM/c7fDk8////fz38/Do3dfRyLu2sqilrbGQOgAAAQAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgiRnGdxNzv+f////39/fr39fbz8PLx6urq8P35+fbt7vDy+P/87O3u8v//5drXzMfE" +
  "wL23w8G3u8jHx8fGy83C3v/y8Pv49/3//f/9+PHs4uDg5uHg2t3g5vDt7fDu//v29vb18/Dq5NzNxbuupqavraJaBgABAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAgIDAwIAAAAAAAASLUZieo6eq7nL1uDm7fX4+vr38u7q4cbY/f//" +
  "+vf6/+/u7/L//+/g2tfT0c3Ixc7Tzc/P0tHV3uTk07zE7vXu+P38/P/////79fHq5urv8/X2+Pv78+7/uH3/+fDz9/j48erl" +
  "3dbOwK2vsq+ws3cgAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQIDAwIAAAAAAAAAAAAAAw0W" +
  "HSYyPUZMS0c9LhoCD06It9zs9v//////////9vDd2M7OztXY2drY2ODj6/Pz2sPArqPF6u3t+v//+/v///n59e3o5Orx+Pn4" +
  "9/j///9bQu//8PHw7ezs7Ozo4NnOx8TAxMq7pFYAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAECAwMDAwICAQAAAAAAAAAAAAAAAAAAAAAAAAARKDdMZXyMoa+3vbLB7dvW19vd3uHl4eHq8fny48zL08zLx9Lr8+fj" +
  "7vb7/f/48/fy7urq7O/y9fb2+ffy7TEo0P/u6+jr7/Dx7+vn4NPOzc7AwLuqfRYAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEBAgIDAwMDAwMCAQEBAwMBAAAAAAAAAAAAAAAABYf47uDg5eXm5ePn" +
  "7u/u6ODi6ubV1dvn8PH27uHa3ef1//////nz8O3q6Ovr7fHu5+vcHQ6b9/rt7vP19fbx8Ovk2tPNxczM2dmlGgACAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAECAgMDAwMC" +
  "AQAAAQAAWN7x3uLn6+vo5ubq5uLi29ji8fb19vv/ZUlVUkg5LVPg////+Pb16+fo6+zu6ufg5boMAEOy9vfu8vf49fLy7evm" +
  "4uDe4tvMyKctAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAABAgAiq/Hw6Ovt7Obj5+jn3t7n9fr8///5/5AAAAAAAAAAMfX5/Pv28u/r5+fn5ujs6OPz" +
  "hwAAAFXL+vv58/Ly8PLz9fHu6+bb09LYtjcAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAABNufX87+fj5ufr5+bs8fP19ff6/PX2OwAFAwICBQCn" +
  "//j9+fDw7+vn6Ofq6Ort7eglAwMADGCu3PX/+PL19e/u7u3k3Nrc3d61IQABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAABBhq7M8ejn6O3x9vv8" +
  "/fz7+/Ps88gRAgEAAAIBMvX6+/z48+/r6uro6+zx9vP/mAADAwAAABQ2bej89ffy7Orm4t7c2+Hi2HkYAgEAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAMAAAAADJPw4+zv8vb6+vn49vPq4+H3iAADAAAAAgB5//bz9vPu6ujs7O3y+vv6+PEyAAIBAwEAAAA64v3w8u/o5OTl5uvm" +
  "5dKwVwACAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAIDAgAFwufm7vL18/Ly8O/t5+Tk5eowAAIAAAEDAIz/+fn39fXx7fDx8/f3+PX5qwcCAQAA" +
  "AQIEADHR++/w7Ort6+fq5+bb3LhFAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAE7x4uzw8vLy8e/t7u3u8O//swACAQAAAQIAi//5+Pr7" +
  "9/Lx8fLy9ff39vVlAAMAAAAAAAMAG7f/8fP18u/r5+bm59fNyncLAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAgfjr7+/w8O/v8PHz8/f7" +
  "+f+NAAIAAAABAgB8///2+fjy7/Dy8fb5+vn41x4AAgAAAAAAAwAFjf379fbz7+fg4ubkzsHLoSEAAQAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB" +
  "AgCL9ufr7uzs7vLz9/r8/fz3/1gAAgAAAAECAFjl//z38u7u8fX4+fr79vubAgEAAAAAAAACAABZ4f/28vHw5eXs7eHHwc7E" +
  "OgACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAECAHz37+Tr7vD2+vv6/P//9vjdFgEBAAAAAAMAFn31/fjz8fL19vr9+/jv3C4AAgAAAAAAAAEC" +
  "ABye9v/88+7q7e7s2NLb9k8AAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQIAWNj47O/w8Pb4+Pz8+/z6/4QAAwAAAAAAAwAAkP/28/Dw8fL2" +
  "9/f37+1iAAIAAAAAAAAAAAMAADSLy/H//////fj45nIAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgATe+3t7+vu9vn7/f///P/jEwAB" +
  "AAAAAAAEAzPv+vj28vDu7/P39vX3ewIBAAAAAAAAAAAAAQIAAAQsXouru7ylcB4AAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAACt" +
  "8Obr7fD1+vz7/f/9/04AAwAAAAAAAAIBpP/7+vbx6+7z+ff45H0AAgAAAAAAAAAAAAAAAgMAAAAAAAAAAAAAAgAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAMCNufm6O3x8/f5+f3//P95AAIAAAAAAAACACjw//v39fDu8vn67ejmNgACAAAAAAAAAAAAAAAAAQID" +
  "AwIBAQIDAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgCN/+fw7vL3+fr7+fnqrSUAAQAAAAAAAAMAbP/3/Pnz8vL1+PDw88IY" +
  "AAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAECDLv/6+/v8/j5+vnz/eBFAQIAAAAAAAAA" +
  "AwCs//b69vDu7/X29uXqmgIBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAMuP/w7vDz" +
  "9vr4+fX9fQACAAAAAAAAAAIBG9D/9/Hv7Ovx8ffs4eRcAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAACAAaT///x8vf5+/ru6OArAAIAAAAAAAAAAQATkPX/+O3q7e3x6+X6rgQBAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAEbK///69fX36+LzmwACAAAAAAAAAAABAAAumur////////ukBgBAQAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQMAAVW98/////PevVwBAQAAAAAAAAAAAAECAAAZ" +
  "WY2qqpxzLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAB5DWFY7HQUA" +
  "AAAAAAAAAAAAAAAAAAIDAAAAAAAAAAACAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAwEAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAEDAwICAwQCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgMDAwIBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==";

let cached: Uint8Array | null = null;

/** Decode once; the field only needs the grid when it first mounts. */
export function getHandModelBrightness(): Uint8Array {
  if (cached) return cached;
  const binary = atob(HAND_MODEL_BASE64);
  const grid = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) grid[i] = binary.charCodeAt(i);
  cached = grid;
  return grid;
}
